name: Save Compiled PDF to Repository

on:
  workflow_run:
    workflows: ["Compile LaTeX Document"]
    types:
      - completed

jobs:
  save_pdf:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download compiled PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: compiled-pdf
          path: ./compiled-pdfs

      - name: Commit and push PDF
        run: |
          mkdir -p compiled-pdfs
          mv ./compiled-pdfs/main.pdf ./compiled-pdfs/main-latest.pdf
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add compiled-pdfs/
          git commit -m "📄 Auto-update compiled PDFs [skip ci]" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main
