name: Save Compiled PDF to Repository

on:
  workflow_run:
    workflows: ["Compile LaTeX Document"]
    types:
      - completed

jobs:
  save_pdf:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download compiled PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: compiled-pdf
          path: ./compiled-pdfs

      - name: Update CHANGELOG and latest PDF
        run: |
          mkdir -p compiled-pdfs
          cd compiled-pdfs
          
          # Set main-latest.pdf
          LATEST=$(ls main-CL*.pdf 2>/dev/null | head -1)
          if [ ! -z "$LATEST" ]; then
            cp "$LATEST" main-latest.pdf
          fi

          # Update changelog
          if [ ! -f CHANGELOG.md ]; then
            echo "# PDF Compilation History" > CHANGELOG.md
            echo "" >> CHANGELOG.md
          fi

          echo "## Latest Compilation - $(date -u)" >> CHANGELOG.md
          echo "- **Files:** $(ls *.pdf | wc -l) PDFs" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          cd ..

      - name: Commit PDFs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📄 Save compiled PDFs [skip ci]"
          file_pattern: 'compiled-pdfs/*'
